name: test

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [g++, clang++]
        exclude:
          - os: windows-latest
            compiler: g++

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.compiler }}
        shell: bash

      - name: Build
        run: cmake --build build
        shell: bash
